@host=http://localhost:8080
@contatoId=645fc624cada2c00b9fffe12
#645eb4fae663602f2163cb36
#645fd6a6e630d7401f53632b

###
POST {{host}}/api/v1/contatos HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "nome": "Igor",
    "endereco": {
        "cidade": "Rio Grande",
        "bairro": "Nossa Senhora dos Navegantes"
    },
    "telefones": [
        {
            "ddd": 53,
            "numero": "991234567"
        }
    ]
}

###
PUT {{host}}/api/v1/contatos/{{contatoId}} HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "nome": "Gustavo",
    "endereco": {
        "cidade": "Rio Grande",
        "bairro": "Centro",
        "rua": "Fransisco Marques"
    },
    "telefones": [
        {
            "ddd": 53,
            "numero": "9999998"
        },
        {
            "ddd": 53,
            "numero": "7999997"
        }
    ]
}

###
GET {{host}}/api/v1/contatos?cidade=Rio+Grande HTTP/1.1
Accept: application/json

###
GET {{host}}/api/v1/contatos/{{contatoId}} HTTP/1.1
Accept: application/json

###
GET {{host}}/api/v1/contatos/telefones HTTP/1.1
Accept: application/json

###
DELETE {{host}}/api/v1/contatos/{{contatoId}} HTTP/1.1
Accept: application/json
